---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base/traefik
  - release.yaml
configMapGenerator:
  - name: traefik-triton-values
    files:
      - values.yaml
configurations:
  - ./apps/base/traefik/kustomizeconfig.yaml
