---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-release
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
      version: 34.4.1
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
    - kind: Secret
      name: traefik-secret-values
    - kind: ConfigMap
      name: traefik-triton-values
  interval: 1m0s
