env:
    - name: ENC[AES256_GCM,data:oJj/dxPEmPwk8+Wv9FNSZFKAp0v7rme/,iv:wFQGs5+wCgIoi+Glf9k52d8WebwKoF+3vF6QipLgRnk=,tag:fKCspdFL39JYScuTi0fe3Q==,type:str]
      value: ENC[AES256_GCM,data:Bzu6UiITEU57BSVlCSMgbeF/2/E/vnN270xOkdfQ9kgL/QGthen7oA==,iv:/WGRn8AgsxucKe1mcwdE18EUAivbZ58PSzGAr/tqmKQ=,tag:FL6Fo7s2la+yk3AWKqNvYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-19T17:34:52Z"
    mac: ENC[AES256_GCM,data:fGc1VCpxA6vWkzFvw3D5XE/GATn0nZPwxBm4+hQzT0p3cCoDhZxBKCM1r19hHdRAQULyO4AAVugDLh9QRuZR+rKY2CFBp7ekhHAmz/1eae+91bnYlLDE6k3zJEy9oS8zVKvs1qoB+CNDtNEMmlgTsjSsp0cpFZ8XOMyzqGJik4k=,iv:S17txOZ6/2su194Mla1chxYq0e7CO11IgVVsUPQqKcw=,tag:lKuHvWbIx+Hl6pwKHPb6Sg==,type:str]
    pgp:
        - created_at: "2025-03-19T17:34:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2E9bGEqrsPYAQ/+JuPjLRdIdxgRQQuQcnExeHNjK/Pcp5//B3YvH6askw/O
            oFzknu4T4cutVS7SCn70vx/rLuq9aF5/RfKApdicHi4sXrp4dNJR4ZfNiD5wpdT7
            2Clp8svx8IKXBaLb+3UbdYX3FBmuDqoTgCjKuxHJBvyOmSYMx1FdDHZZIXLsMjNp
            g9aDEuKaG1vrAX7VyY7IMnUF3EKXopEwsB4u2Nnp6PiOqKAicm7EG13LvQNnQgOD
            F+KIbOiGwlNgKuMR6Oht4uz5MbS9MPSmawK3FKtRHHuhE2lVTey+6b4DL7RrFSPA
            y9oNTjp3rpmcjQLj7QIYs94YTAXsUOW4cl6jfGMZv9UaeKHac6Q33pkGbghMNd0A
            dLDiQuvW/EdTgaAEjEWarqnU9drbHp7uLBf9q/4Ay0/Nqu/QIAFZ8gtVa2e9mZU9
            cWfVD2hNronyRvIt/Uh+vrzsirUOogudykgUQChibCkCLOKWNpWfLuU9Rq+cirAx
            32qPKeWOAmenHuaz3q/eelAJSYWW+aeXOQL595sVmbmE+iLigNBGG9scqp2wFzgM
            yEWmOCeaujfgf30lt5hh37QC5jlQ8bFFpZGqzUmNKudp641nhJpA5SdPT7UYbIeV
            whC8UUX/yLpN/oHZWxC1BFSHdjA2DLCeSLE1H6GpSShHIMuQ3QMXVzMEORv4zITU
            aAEJAhBz/5JHXXxZ3LyyYtyb0kBtBc+HSR5skodddkzQW+6UEVfq4f26ZtVDh1Jb
            n9XP+MM4mRlrtZY6vLXr4pcv+mxy5FGJ+5Zm6z4ko8YX8WJGXx8IiUNjxxHh0Ydy
            2XGr86dVsUcb
            =H4SM
            -----END PGP MESSAGE-----
          fp: DD45ABA8538CB7C9D92AFCDF5C29560744044DB2
    unencrypted_suffix: _unencrypted
    version: 3.9.4
